[package]
name = "jira-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
gpui.workspace = true
gpui-component.workspace = true
jira-application = { path = "../../crates/application" }
jira-desktop-notifications = { path = "../../crates/desktop-notifications" }
jira-domain = { path = "../../crates/domain" }
jira-http = { path = "../../crates/jira-http" }
jira-storage = { path = "../../crates/storage" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gpui_platform = { version = "0.1.0", git = "https://github.com/zed-industries/zed", default-features = false, features = ["wayland"] }
gpui-component-assets = { version = "0.5.1", git = "https://github.com/longbridge/gpui-component", rev = "b29ee13379e161c2fb68c14c229c958d52d6ffe4" }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
futures-lite = "2.6.1"

[lints]
workspace = true
